version: '3'
services:
  frontend:
    build: ./frontend
    container_name: bm_front
    command: npm start
    ports:
      - 3000:3000
    volumes:
      - ./frontend:/usr/app
    depends_on:
      - backend
  backend:
    build: ./backend
    container_name: bm_back
    ports:
      - 3001:3001
    volumes:
      - ./backend:/usr/app
    depends_on:
      - database
  database:
    container_name: bm_db
    image: mysql:8.0.29
    ports:
      - 3006:3006
    environment:
      MYSQL_ROOT_PASSWORD: root